project:
  type: website
  output-dir: docs

website:
  title: "Renata Diaz, PhD"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: papers.qmd
      - text: "Software and data"
        href: software.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Resume"
        href: cv.qmd
      - text: "Contact"
        href: contact.qmd
      - text: "GitHub"
        href: https://github.com/diazrenata

format:
  html:
    theme: simplex
    css: styles.css
    toc: true



