---
  title: "Research themes"
---

## Statistical constraints on macroecological patterns

Macroecological patterns - such as "hollow curve" species abundance distributions, or multimodal size distributions - emerge via a combination of ecological processes and potentially very strong statistical constraints. In order to understand the ecological processes that contribute to the patterns observed in nature, it is necessary to disentangle any ecological signal from the patterns that emerge from just the statistical constraint. 

With data from >20,000 ecological communities, we have shown that [empirical species abundance distributions are consistently much more uneven than would be expected given the statistical constraint](https://doi.org/10.1111/ele.13820). 

## Macroecological dynamics of community structure

I use long-term data on the species composition, size structure, and community-level properties (species richness, total abundance, and total energy use) of ecological communities to study how communities change over time and how changes at smaller levels of organization propagate to the community scale.

Working with a 40-year experimental manipulation of the rodent community near Portal, AZ, I am investigating how environmental change and metacommunity dynamics determine the extent to which community level energy use is resilient to species extinctions. 

At a cross-community, continental scale, I am investigating how the size structure of North American breeding bird communities has shifted over the past 40 years, and how these shifts modulate trends in total abundance and energy use.

Working in collaboration with members of [Weecology](https://www.weecology.org), I am using machine learning and Bayesian changepoint analysis to explore the frequency and timing of rapid reorganization events in the community composition of North American breeding bird communities. 

## Open, reproducible research

I develop approaches and infrastructure to facilitate open, reproducible access to ecological data and to implement new statistical methods in ecology. See [Software and data products](opensci.html) for details. 