---
title: "CV"
---

### Renata Diaz

### Education

##### PhD in Interdisciplinary Ecology - University of Florida - 2017-present
* School of Natural Resources and Environment
* Dept. of Wildlife Ecology and Conservation
* Weecology Lab

##### A.B. in Ecology & Evolutionary Biology - Princeton University - 2015
* High honors
* Certificate in Environmental Studies

### Publications
* Portal workflow paper

### Software and data products
* `portalr`
* `LDATS`
* `MATSS`
* Portal data paper

### Research experience
##### The Portal Project - 2017-present
* Monthly rodent censuses with volunteer assitants
* Annual plant censuses

##### Missouri Botanical Garden Global Change Biology Lab - 2017
* Spatial analysis of threats to rare plants in the United States

##### The Ecology of Bird Loss Project - 2016
* Fieldwork and data management on tropical forests in Guam & the Marianas Islands

##### The Staver Lab - 2015-2016 
* Field, lab, and greenhouse work on the effects of fire and drought on African savanna trees

### Teaching and mentoring experience
* Undergraduate CV workshops and volunteer field opportunities

### Skills
* Advanced R and git
* High performance computing
* Collaborative computational research

