---
  title: "Open and reproducible research"
---

# R packages

#### 

#### [portalr](https://weecology.github.io/portalr/)

Tools to download & access summaries of data from the [Portal Project](https://www.weecology.org/project/portal/). 


#### [LDATS](https://weecology.github.io/LDATS/)

Combines **L**atent **D**irichlet **A**llocation with Bayesian changepoint-analysis of **t**ime-**s**eries to detect rapid transitions in ecological community composition. Building on the analysis in [Christensen et al. 2018](https://doi.org/10.1002/ecy.2373).


#### [MATSS](https://weecology.github.io/MATSS/)

**M**acroecological **A**nalysis of **T**ime-**s**eries **S**tructure. Load numerous ecological timeseries datasets in a standardized format, and build flexible piplines using [`drake`](https://books.ropensci.org/drake/) or similar packages.


#### [feasiblesads](https://github.com/diazrenata/feasiblesads)

Draw samples from the [feasible set](https://doi.org/10.1111/ele.12154) for a species abundance distribution.


#### [cvlt](https://diazrenata.github.io/cvlt/)

(In dev.) Cross-validation functions to apply `LDATS` to short, high-dimensional timeseries.



# Replication reports

#### replicate-becs

Replication of [Ernest (2005): Body size, energy use, and community structure of small mammals](https://doi.org/10.1890/03-3179). In prep, for submission to [ReScience C](https://rescience.github.io/). 

https://github.com/diazrenata/replicate-becs


