---
  title: "Research themes"
---


# Perturbations and reorganization in community structure

I use long-term field experiments and synthesis across timeseries to study how change propagates over time and across levels of organization in ecological systems. 

Working with a 40-year experimental manipulation of the rodent community near Portal, AZ, I am investigating [how long-term environmental change and abrupt changes in species composition modulate the extent to which system-level properties are resilient to species extinctions](https://doi.org/10.1002/ecy.3709). 

At a cross-community, continental scale, I am investigating how the size structure of North American breeding bird communities has shifted over the past 40 years, and how these shifts modulate trends in total abundance and energy use.

Working in collaboration with members of [Weecology](https://www.weecology.org), I am using machine learning methods for text analysis and Bayesian changepoint analysis (implemented in the R packages [LDATS](https://weecology.github.io/LDATS/) and [cvlt](https://diazrenata.github.io/cvlt/)) to explore the frequency and timing of rapid reorganization events in the community composition of North American breeding bird communities. 

# Complexity in community ecology

Ecological systems are notoriously difficult to predict in specific detail (e.g. the exact abundance of a particular species at a particular site), but often exhibit consistent behaviors in the aggregate (e.g. "hollow-curve" distributions of abundance across all species in a system). In this regard, ecological systems are analogous to complex systems from across the sciences. I borrow theoretical frameworks developed across the range of complex-systems disciplines to link pattern to process in community ecology.  

## Statistical baselines for ecological patterns

```{r, include = T, echo = F, message = F, warning = F, fig.dim = c(3.5,2)}
library(dplyr)
some_sads <- feasiblesads::sample_fs(10, 200, 50) %>% as.data.frame() %>% mutate(sim = dplyr::row_number()) %>% tidyr::pivot_longer(-sim, names_to = "sp", values_to = "abund") %>% group_by(sim) %>% arrange(abund) %>% mutate(sp = row_number()) %>% ungroup()
library(ggplot2)
ggplot(some_sads, aes(sp, abund, color = sim, group = as.factor(sim))) + geom_line() + scale_color_viridis_c(option = "mako") + theme_minimal() + theme(legend.position = "none") + xlab("Rank")+ ylab("Abundance") + theme(panel.grid = element_blank())

```

Common patterns in ecology - such as "hollow-curve" species abundance distributions, above - result from a combination of ecological processes and ubiquitous mathematical constraints on the emergent forms for abundance distributions in complex systems in general. Historically, these mathematical constraints have presented an obstacle to using these patterns to understand *ecology* - but they can also be a powerful tool for detecting and diagnosing strong disruptive processes at play in ecological systems. Deviations between real patterns and their idealized theoretical forms can reflect strong ecological processes. Isolating these deviations allows for stronger inference about ecology than trying to account for the general, mathematically-determined, pattern. Using data from >20,000 ecological communities, and a little bit of [combinatorics](https://github.com/diazrenata/feasiblesads), we have shown that [empirical species abundance distributions are consistently much more uneven than would be expected given the statistical constraint](https://doi.org/10.1111/ele.13820). 

## Ecological communites as nontraditional complex systems

At the same time, ecological systems are different from more traditional "complex" systems in physics and statistics, and may not play by the same rules that apply in those disciplines. Ecological systems are often small, with incomplete or imperfect observations of actual organisms, and constrained by their ecological and evolutionary histories. When we borrow theoretical approaches from other contexts, we need to adapt them to work with the idiosyncracies of ecological data. This can teach us about both ecology, and about how complex phenomena come to be in the first place and when and why they break down. Building on initial work with ecological abundance distributions (above), I am exploring how the nature and inferential power of mathematical constraints on abundance distributions varies across systems of different sizes and levels of sampling resolution.



# Open, reproducible research

I develop approaches and infrastructure to facilitate open, reproducible access to ecological data and to implement new statistical methods in ecology. See [Software and data products](opensci.html) for details. 